# POST https://192.168.137.1:7000/user/addComment HTTP/1.1
# content-type: application/json

# {
#     "userId": 1,
#     "articleId": 1,
#     "commentContent": "wwwwwwwwwwwwww"
# }

POST  http://192.168.137.1:7000/default/getFavArticle HTTP/1.1
Content-Type: application/json

{
    "favId": 1,
    "pageNum": 1
}

